### ISSUE TITLE
Looking to get my server listed...

### ISSUE THREAD

**Issue by fstltna** [rjhancock/megamek-games#39]
server dns: mekwars.mekcity.com
server dns: 2600:3c01::f03c:93ff:fe9e:c4b2
port: 2346
name: MekWars @ MekCity.com Project
Faction: Steiner

Thanks!

**Comment by rjhancock** [comment]
I get that it's MekWars but is it the custom MekWars client or a MegaMek one?

And sorry for the late response. Has been exceedingly busy.

**Comment by fstltna** [comment]
> I get that it's MekWars but is it the custom MekWars client or a MegaMek one?

The custom MekWars client I believe...

**Comment by rjhancock** [comment]
Not that we don't appreciate the MekWars client for it, this is meant specifically for the MegaMek servers. I'll talk with Hammer to see if he thinks we should add a section for MekWars.

**Comment by rjhancock** [comment]
Added
