### ISSUE TITLE
Raila's Raiders: New clients, Port changes, updates to dev server

### ISSUE THREAD

**Issue by Sierra-Invenio** [rjhancock/megamek-games#42]
Spun up another group of stables, 3 new devs, updated existing dev to current version

Enclosed is edited index.md file, I just can't figure out how to make a branch.

Online ETA less than 10mins.

[index.md](https://github.com/rjhancock/megamek-games/files/13199239/index.md)

**Comment by rjhancock** [comment]
Please don't like the updated file just post the changes you want done.

**Comment by Sierra-Invenio** [comment]
Sorry,

New servers: stable

`
|ralias-raiders. megamek.games|3039|0.48.0|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3052|0.48.0|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3058|0.48.0|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3062|0.48.0|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3067|0.48.0|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3081|0.48.0|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
`

New servers: dev
`
|ralias-raiders. megamek.games|2823|0.49.15|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3049|0.49.15|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3057|0.49.15|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
|ralias-raiders. megamek.games|3071|0.49.15|2048M - Regimental?|Sierra Invenio / SniperTeamTango|
`

3049 is just updated to 0.49.15

**Comment by rjhancock** [comment]
Updated.
